// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct Factorial
{
  struct Factorial_vtable *vptr;
};
struct Fac
{
  struct Fac_vtable *vptr;
};

// vtables structures
struct Factorial_vtable
{
  char *Factorial_gc_map;
};

struct Fac_vtable
{
  char *Fac_gc_map;
  int (*ComputeFac)();
};


// pointing to f's caller's GC frame
void *prev;

// methods
struct ComputeFac_gc_frame 
{
  void *prev;
  int arguments_gc_map;
  int *arguments_base_address;
  int local_gc_map;
  int num_aux;
  struct Fac * x_2;
};

int Fac_ComputeFac(struct Fac * this, int num)
{
  int num_aux;
  struct Fac * x_2;

  int f_arguments_gc_map = 1;
  int f_locals_gc_map = 1;
  struct ComputeFac_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = 1;
  frame.arguments_base_address = &this;
  frame.local_gc_map = 1;
  if (num < 1)
    num_aux = 1;
  else
    num_aux = num * (x_2=this, x_2->vptr->ComputeFac(x_2, num - 1));
  return num_aux;
}

// vtables
struct Factorial_vtable Factorial_vtable_ = 
{
  "", 
};

struct Fac_vtable Fac_vtable_ = 
{
  "", 
  Fac_ComputeFac
};


// main method
int Tiger_main ()
{
  struct Fac * x_1;
  System_out_println ((x_1=((struct Fac*)(Tiger_new (&Fac_vtable_, sizeof(struct Fac)))), x_1->vptr->ComputeFac(x_1, 10)));
}




